import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { renderGoogleServices } from "./render.mjs";

const [filename, tag, outputDirectory] = process.argv.slice(2);
if (!filename || !/^v\d+\.\d+\.\d+$/u.test(tag || "") || !path.isAbsolute(outputDirectory || "")) throw new Error("Konfiguration, Produkt-Tag und geschütztes externes Ausgabeverzeichnis erforderlich.");
const run = (command, args, options = {}) => execFileSync(command, args, { stdio: "inherit", ...options });
const read = (command, args) => run(command, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
const root = fs.realpathSync(read("git", ["rev-parse", "--show-toplevel"]));
const output = fs.realpathSync(outputDirectory);
if (output === root || output.startsWith(root + path.sep) || (fs.statSync(output).mode & 0o077) !== 0) throw new Error("Ausgabe muss außerhalb von Git und owner-only sein.");
if (read("git", ["status", "--porcelain"])) throw new Error("Der Release-Checkout ist nicht sauber.");
const config = JSON.parse(fs.readFileSync(filename, "utf8"));
renderGoogleServices(config);
run("git", ["fetch", "--prune", "origin"]);
const revision = read("git", ["rev-parse", `${tag}^{}`]);
if (read("git", ["rev-parse", "HEAD"]) !== revision) throw new Error("HEAD muss exakt dem signierten Produkt-Tag entsprechen.");
run("git", ["merge-base", "--is-ancestor", revision, "origin/main"]);
const repository = "TimoFrank/mitmachen";
const metadata = JSON.parse(read("gh", ["release", "view", tag, "--repo", repository, "--json", "tagName,name,isDraft,isPrerelease,isImmutable"]));
const releases = JSON.parse(read("gh", ["release", "list", "--repo", repository, "--limit", "1000", "--json", "tagName,isLatest"]));
metadata.isLatest = releases.find((entry) => entry.tagName === tag)?.isLatest;
const tagObject = read("git", ["rev-parse", `refs/tags/${tag}`]);
const remoteObject = read("git", ["ls-remote", "--refs", "--tags", "origin", `refs/tags/${tag}`]).split(/\s/u)[0];
if (remoteObject !== tagObject) throw new Error("Lokales und veröffentlichtes Tagobjekt weichen ab.");
const metadataPath = path.join(output, "release-metadata.json");
const verificationPath = path.join(output, "release-verification.json");
fs.writeFileSync(metadataPath, JSON.stringify(metadata), { mode: 0o600 });
fs.writeFileSync(verificationPath, read("gh", ["api", `repos/${repository}/git/tags/${tagObject}`]), { mode: 0o600 });
const publicKey = read("gh", ["variable", "get", "RELEASE_TAG_GPG_PUBLIC_KEY", "--repo", repository]);
const fingerprint = read("gh", ["variable", "get", "RELEASE_TAG_GPG_FINGERPRINT", "--repo", repository]);
const keyDirectory = fs.mkdtempSync(path.join(output, "release-verification-"));
const environment = { ...process.env, GNUPGHOME: keyDirectory };
run("gpg", ["--batch", "--import"], { input: publicKey, env: environment });
run("node", ["scripts/verify_release_tag.mjs", "--tag", tag, "--commit-sha", revision, "--fingerprint", fingerprint, "--expected-title", metadata.name, "--remote-tag-object-sha", remoteObject, "--github-verification-json", verificationPath, "--published-release-metadata-json", metadataPath], { env: environment });
if (JSON.parse(fs.readFileSync("config/release.json")).productVersion !== tag.slice(1)) throw new Error("Produktversion und Tag stimmen nicht überein.");
run("node", ["scripts/build_google_hosting.mjs"], { env: { ...process.env, API_BASE_URL: config.origin, IAP_EXTERNAL_AUTH_API_KEY: config.apiKey, IAP_GCIP_PROJECT_ID: config.project } });
const imageTag = `${config.region}-docker.pkg.dev/${config.project}/versorgungs-kompass-pre-gematik/versorgungs-kompass-google-hosting:${tag}-${revision.slice(0, 12)}`;
const buildMetadata = path.join(output, "image-build.json");
run("docker", ["buildx", "build", "--platform", "linux/amd64", "--file", "deploy/google-hosting/Dockerfile", "--tag", imageTag, "--build-arg", `PRODUCT_VERSION=${tag.slice(1)}`, "--build-arg", `SOURCE_REVISION=${revision}`, "--build-arg", `SOURCE_URL=https://github.com/${repository}`, "--metadata-file", buildMetadata, "--provenance=true", "--push", "."]);
const digest = JSON.parse(fs.readFileSync(buildMetadata))["containerimage.digest"];
if (!/^sha256:[a-f0-9]{64}$/u.test(digest || "")) throw new Error("Der gebaute Image-Digest fehlt.");
const candidate = { ...config, revision, image: `${imageTag.split(":")[0]}@${digest}`, cutoverMode: "closed" };
const services = renderGoogleServices(candidate);
fs.writeFileSync(path.join(output, "release-config.json"), JSON.stringify(candidate, null, 2) + "\n", { mode: 0o600 });
for (const [name, value] of Object.entries(services)) fs.writeFileSync(path.join(output, `${name}.json`), JSON.stringify(value, null, 2) + "\n", { mode: 0o600 });
console.log(`Geprüfter Release ${tag}, ${revision}, ${digest}; Umschaltzustand geschlossen.`);
