apiVersion: v1
kind: ServiceAccount
metadata:
  name: vk-pre-gematik-migration-operator
  namespace: pre-gematik
  labels:
    app.kubernetes.io/name: versorgungs-kompass
    app.kubernetes.io/component: migration-operator
automountServiceAccountToken: false
