import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const outputPath = process.argv[2] || "/tmp/versorgungs-kompass-postgres-import.sql";
const root = process.cwd();

const tables = [
  "profiles",
  "organizations",
  "contacts",
  "contact_owners",
  "changes",
  "saved_views",
  "user_settings",
  "login_aliases",
  "notification_events",
  "notification_recipients",
  "formats",
  "format_participants",
  "hospitation_slots",
  "hospitations",
  "expert_groups",
  "expert_organizations",
  "expert_contacts",
  "expert_entity_links",
  "stakeholder_types",
  "stakeholder_organizations",
  "stakeholder_people"
];

const truncateTables = [
  "notification_recipients",
  "notification_events",
  "user_settings",
  "saved_views",
  "login_aliases",
  "contact_owners",
  "changes",
  "format_participants",
  "hospitations",
  "hospitation_slots",
  "formats",
  "expert_entity_links",
  "expert_contacts",
  "expert_organizations",
  "expert_groups",
  "stakeholder_people",
  "stakeholder_organizations",
  "stakeholder_types",
  "contacts",
  "organizations",
  "import_runs",
  "profiles"
];

const jsonbColumns = new Set([
  "import_runs.report",
  "saved_views.filters",
  "user_settings.preferences",
  "notification_events.payload",
  "hospitations.requested_windows"
]);

const arrayColumns = new Set([
  "contacts.topics",
  "expert_contacts.topics",
  "expert_contacts.owner_ids",
  "hospitations.topics",
  "stakeholder_people.topics"
]);

function quoteIdent(value) {
  return `"${String(value).replace(/"/g, '""')}"`;
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlTextArray(values) {
  if (!Array.isArray(values)) return "ARRAY[]::text[]";
  return `ARRAY[${values.map((value) => `${sqlString(value)}::text`).join(", ")}]::text[]`;
}

function sqlValue(table, column, value) {
  if (value === null || value === undefined) return "NULL";
  const key = `${table}.${column}`;
  if (arrayColumns.has(key)) return sqlTextArray(value);
  if (jsonbColumns.has(key)) return `${sqlString(JSON.stringify(value))}::jsonb`;
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "object") return `${sqlString(JSON.stringify(value))}::jsonb`;
  return sqlString(value);
}

function extractJsonObject(source) {
  const boundaryIndex = source.indexOf('"boundary"');
  if (boundaryIndex < 0) throw new Error(`Supabase CLI returned no JSON boundary:\n${source.slice(0, 500)}`);
  const start = source.lastIndexOf("{", boundaryIndex);
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let index = start; index < source.length; index += 1) {
    const char = source[index];
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }
    if (char === "\"") {
      inString = true;
      continue;
    }
    if (char === "{") depth += 1;
    if (char === "}") {
      depth -= 1;
      if (depth === 0) return source.slice(start, index + 1);
    }
  }
  throw new Error("Supabase CLI JSON payload was incomplete.");
}

function queryRows(table) {
  const sql = `select coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb) as data from public.${table} t;`;
  const stdout = execFileSync("supabase", ["db", "query", "--linked", sql], {
    cwd: root,
    encoding: "utf8",
    maxBuffer: 50 * 1024 * 1024,
    stdio: ["ignore", "pipe", "pipe"]
  });
  const parsed = JSON.parse(extractJsonObject(stdout));
  return parsed.rows?.[0]?.data || [];
}

function insertSql(table, rows) {
  if (!rows.length) return `-- ${table}: 0 rows\n`;
  const columns = Object.keys(rows[0]);
  const quotedColumns = columns.map(quoteIdent).join(", ");
  const overriding = table === "changes" && columns.includes("id") ? " overriding system value" : "";
  const chunks = [];
  for (const row of rows) {
    const values = columns.map((column) => sqlValue(table, column, row[column])).join(", ");
    chunks.push(`insert into ${quoteIdent(table)} (${quotedColumns})${overriding} values (${values});`);
  }
  return [`-- ${table}: ${rows.length} rows`, ...chunks].join("\n") + "\n";
}

const schema = fs.readFileSync(path.join(root, "db/postgres/schema.sql"), "utf8");
const parts = [
  "-- Generated by scripts/build_postgres_import_from_supabase.mjs",
  `-- Generated at ${new Date().toISOString()}`,
  "begin;",
  schema,
  `truncate table ${truncateTables.map(quoteIdent).join(", ")} restart identity cascade;`
];

const summary = {};
for (const table of tables) {
  const rows = queryRows(table);
  summary[table] = rows.length;
  parts.push(insertSql(table, rows));
}
parts.push("select setval(pg_get_serial_sequence('changes', 'id'), greatest(coalesce((select max(id) from changes), 0), 1), true);");
parts.push("commit;");

fs.writeFileSync(outputPath, parts.join("\n\n"));
console.log(JSON.stringify({ outputPath, summary }, null, 2));
