import { execFileSync } from "node:child_process";

const syntaxFiles = [
  "api/password-reset-broker.mjs",
  "api/password-reset-server.mjs",
  "api/security-policy.mjs",
  "api/test-access-enrollment.mjs",
  "api/typo3-registration-connector.mjs",
  "api/request-log-privacy.mjs",
  "api/care-sector-model.mjs",
  "api/bundestag-health-committee.mjs",
  "api/duplicate-identity.mjs",
  "api/hospitation-import.mjs",
  "api/server.mjs",
  "frontend/app/versorgungs-kompass-routes.js",
  "frontend/app/hospitation/import.js",
  "frontend/data/activity-model.js",
  "frontend/data/data-service.js",
  "frontend/data/demo-api.js",
  "frontend/data/demo-data.js",
  "frontend/data/public-politics-directory.js",
  "frontend/data/document-text-extractor.js",
  "frontend/data/hospitation-export.js",
  "frontend/login/auth-guard.js",
  "scripts/audit_api_gateway.mjs",
  "scripts/audit_public_assets.mjs",
  "scripts/audit_target_assets.mjs",
  "scripts/audit_stakeholder_fields.mjs",
  "scripts/check_gcp_autopilot_readiness.mjs",
  "scripts/check_pre_gematik_migration_gcp.mjs",
  "scripts/check_deployment_governance.mjs",
  "scripts/check_release_policy.mjs",
  "scripts/check_markdown_language.mjs",
  "scripts/check_project.mjs",
  "scripts/check_target_readiness.mjs",
  "scripts/extract_inline_frontend_assets.mjs",
  "scripts/generate_frontend_sbom.mjs",
  "scripts/generate_module_brand_assets.mjs",
  "scripts/generate_security_evidence.mjs",
  "scripts/generate_pre_gematik_synthetic_seed.mjs",
  "scripts/hash_pre_gematik_migration_contract.mjs",
  "scripts/lib/cloud-sql-managed-proxy.mjs",
  "scripts/lib/release_projection.mjs",
  "scripts/lib/release_policy.mjs",
  "scripts/normalize_repository_url.mjs",
  "scripts/package_product_release.mjs",
  "scripts/print_product_version.mjs",
  "scripts/prepare_weekly_release.mjs",
  "scripts/prepare_target_frontend_config.mjs",
  "scripts/preflight_target_deployment.mjs",
  "scripts/prepare_pre_gematik_identity_operator.mjs",
  "scripts/prepare_pre_gematik_test_access_allowlist_operator.mjs",
  "scripts/prepare_pre_gematik_test_access_operator.mjs",
  "scripts/provision_iap_identity_bindings.mjs",
  "scripts/provision_pre_gematik_identity_platform_account.mjs",
  "scripts/provision_pre_gematik_identity_platform_google_user.mjs",
  "scripts/provision_pre_gematik_identity_platform_guest_access.mjs",
  "scripts/render_pre_gematik_guest_welcome_email.mjs",
  "scripts/send_pre_gematik_guest_welcome_email.mjs",
  "scripts/provision_pre_gematik_test_access_allowlist.mjs",
  "scripts/provision_pre_gematik_test_access.mjs",
  "scripts/run_hospitation_import_duplicate_cleanup.mjs",
  "scripts/test_activity_model.mjs",
  "scripts/test_activity_pagination.mjs",
  "scripts/test_consent_schema.mjs",
  "scripts/test_contact_notes_schema.mjs",
  "scripts/test_cloud_run_decommission.mjs",
  "scripts/test_clean_url_routes.mjs",
  "scripts/test_care_sector_model.mjs",
  "scripts/test_format_participation_schema.mjs",
  "scripts/test_frontend_sbom.mjs",
  "scripts/test_pre_gematik_guest_welcome_email_send.mjs",
  "scripts/test_demo_api.mjs",
  "scripts/test_duplicate_identity.mjs",
  "scripts/test_hospitation_demo_data.mjs",
  "scripts/test_hospitation_document_export.mjs",
  "scripts/test_global_duplicate_guards_postgres_e2e.mjs",
  "scripts/test_hospitation_import_contract.mjs",
  "scripts/test_hospitation_import_postgres_e2e.mjs",
  "scripts/test_hospitation_duplicate_cleanup_runner.mjs",
  "scripts/test_hospitation_import_ui.mjs",
  "scripts/test_iap_external_identity.mjs",
  "scripts/test_iap_identity_bindings.mjs",
  "scripts/test_iap_identity_mode_reconcile.mjs",
  "scripts/test_login_bootstrap_hotfix.mjs",
  "scripts/test_legacy_backend_decommission.mjs",
  "scripts/test_request_log_privacy.mjs",
  "scripts/test_stakeholder_logo_contract.mjs",
  "scripts/test_target_frontend_config.mjs",
  "scripts/test_typo3_registration_connector.mjs",
  "scripts/test_deployment_separation.mjs",
  "scripts/test_api_postgres_contracts.mjs",
  "scripts/test_api_test_access.mjs",
  "scripts/test_api_runtime_config.mjs",
  "scripts/test_password_reset_broker.mjs",
  "scripts/test_api_validation.mjs",
  "scripts/test_auth_avatar_contract.mjs",
  "scripts/test_avatar_render_stability.mjs",
  "scripts/test_bundestag_health_committee.mjs",
  "scripts/test_profile_avatar_cache.mjs",
  "scripts/test_pre_gematik_postgres_schema.mjs",
  "scripts/test_password_reset_deployment_contract.mjs",
  "scripts/test_pre_gematik_iap_workflow.mjs",
  "scripts/test_pre_gematik_auth_helper_proxy.mjs",
  "scripts/test_pre_gematik_identity_platform_guest_access.mjs",
  "scripts/test_pre_gematik_online_onboarding_postgres.mjs",
  "scripts/test_pre_gematik_guest_welcome_email.mjs",
  "scripts/test_pre_gematik_identity_platform_google_user_import.mjs",
  "scripts/test_pre_gematik_identity_platform_onboarding.mjs",
  "scripts/test_pre_gematik_identity_admin_role_postgres.mjs",
  "scripts/test_pre_gematik_test_access.mjs",
  "scripts/test_pre_gematik_test_access_allowlist.mjs",
  "scripts/test_pre_gematik_access_enrollment_role_postgres.mjs",
  "scripts/test_pre_gematik_test_access_allowlist_postgres.mjs",
  "scripts/test_pre_gematik_migration_gcp.mjs",
  "scripts/test_release_policy.mjs",
  "scripts/test_product_release.mjs",
  "scripts/test_product_version_propagation.mjs",
  "scripts/test_release_artifacts.mjs",
  "scripts/test_release_workflow_contracts.mjs",
  "scripts/test_weekly_release.mjs",
  "scripts/update_public_politics_directory.mjs",
  "scripts/update_politics_offline_snapshot.mjs",
  "scripts/test_migration_operator_contract.mjs",
  "scripts/test_security_contracts.mjs",
  "scripts/test_security_evidence.mjs",
  "scripts/verify_product_release.mjs",
  "scripts/verify_release_artifacts.mjs",
  "scripts/verify_release_tag.mjs",
  "scripts/verify_publication_state.mjs"
];

const auditCommands = [
  ["node", ["scripts/generate_module_brand_assets.mjs", "--check"]],
  ["node", ["scripts/audit_public_assets.mjs"]],
  ["node", ["scripts/audit_api_gateway.mjs"]],
  ["node", ["scripts/audit_stakeholder_fields.mjs"]],
  ["node", ["scripts/test_api_validation.mjs"]],
  ["node", ["scripts/test_auth_avatar_contract.mjs"]],
  ["node", ["scripts/test_avatar_render_stability.mjs"]],
  ["node", ["scripts/test_bundestag_health_committee.mjs"]],
  ["node", ["scripts/test_profile_avatar_cache.mjs"]],
  ["node", ["scripts/test_activity_model.mjs"]],
  ["node", ["scripts/test_activity_pagination.mjs"]],
  ["node", ["scripts/test_consent_schema.mjs"]],
  ["node", ["scripts/test_contact_notes_schema.mjs"]],
  ["node", ["scripts/test_cloud_run_decommission.mjs"]],
  ["node", ["scripts/test_clean_url_routes.mjs"]],
  ["npm", ["--prefix", "frontend/identity-portal", "test"]],
  ["node", ["scripts/test_care_sector_model.mjs"]],
  ["node", ["scripts/test_format_participation_schema.mjs"]],
  ["node", ["scripts/test_frontend_sbom.mjs"]],
  ["node", ["scripts/test_hospitation_demo_data.mjs"]],
  ["node", ["scripts/test_demo_api.mjs"]],
  ["node", ["scripts/update_public_politics_directory.mjs", "--check"]],
  ["node", ["scripts/update_politics_offline_snapshot.mjs", "--check"]],
  ["node", ["scripts/test_duplicate_identity.mjs"]],
  ["node", ["scripts/test_hospitation_document_export.mjs"]],
  ["node", ["scripts/test_global_duplicate_guards_postgres_e2e.mjs"]],
  ["node", ["scripts/test_hospitation_import_contract.mjs"]],
  ["node", ["scripts/test_hospitation_import_postgres_e2e.mjs"]],
  ["node", ["scripts/test_hospitation_duplicate_cleanup_runner.mjs"]],
  ["node", ["scripts/test_hospitation_import_ui.mjs"]],
  ["node", ["scripts/test_iap_external_identity.mjs"]],
  ["node", ["scripts/test_iap_identity_bindings.mjs"]],
  ["node", ["scripts/test_iap_identity_mode_reconcile.mjs"]],
  ["node", ["scripts/test_login_bootstrap_hotfix.mjs"]],
  ["node", ["scripts/test_legacy_backend_decommission.mjs"]],
  ["node", ["scripts/test_request_log_privacy.mjs"]],
  ["node", ["scripts/test_stakeholder_logo_contract.mjs"]],
  ["node", ["scripts/test_target_frontend_config.mjs"]],
  ["node", ["scripts/test_typo3_registration_connector.mjs"]],
  ["node", ["scripts/test_deployment_separation.mjs"]],
  ["node", ["scripts/test_api_postgres_contracts.mjs"]],
  ["node", ["scripts/test_api_test_access.mjs"]],
  ["node", ["scripts/test_api_runtime_config.mjs"]],
  ["node", ["scripts/test_password_reset_broker.mjs"]],
  ["node", ["scripts/test_password_reset_deployment_contract.mjs"]],
  ["node", ["scripts/test_pre_gematik_postgres_schema.mjs"]],
  ["node", ["scripts/test_pre_gematik_iap_workflow.mjs"]],
  ["node", ["scripts/test_pre_gematik_auth_helper_proxy.mjs"]],
  ["node", ["scripts/test_pre_gematik_identity_platform_guest_access.mjs"]],
  ["node", ["scripts/test_pre_gematik_online_onboarding_postgres.mjs"]],
  ["node", ["scripts/test_pre_gematik_guest_welcome_email.mjs"]],
  ["node", ["scripts/test_pre_gematik_identity_platform_google_user_import.mjs"]],
  ["node", ["scripts/test_pre_gematik_identity_platform_onboarding.mjs"]],
  ["node", ["scripts/test_pre_gematik_identity_admin_role_postgres.mjs"]],
  ["node", ["scripts/test_pre_gematik_test_access.mjs"]],
  ["node", ["scripts/test_pre_gematik_test_access_allowlist.mjs"]],
  ["node", ["scripts/test_pre_gematik_access_enrollment_role_postgres.mjs"]],
  ["node", ["scripts/test_pre_gematik_test_access_allowlist_postgres.mjs"]],
  ["node", ["scripts/test_pre_gematik_migration_gcp.mjs"]],
  ["node", ["scripts/test_release_policy.mjs"]],
  ["node", ["scripts/test_weekly_release.mjs"]],
  ["node", ["scripts/test_product_release.mjs"]],
  ["node", ["scripts/test_release_artifacts.mjs"]],
  ["node", ["scripts/test_release_workflow_contracts.mjs"]],
  ["node", ["scripts/test_product_version_propagation.mjs"]],
  ["node", ["scripts/test_migration_operator_contract.mjs"]],
  ["node", ["scripts/test_security_contracts.mjs"]],
  ["node", ["scripts/test_security_evidence.mjs"]],
  ["node", ["scripts/check_gcp_autopilot_readiness.mjs"]],
  ["node", ["scripts/check_deployment_governance.mjs"]],
  ["node", ["scripts/check_release_policy.mjs"]],
  ["node", ["scripts/check_markdown_language.mjs"]],
  ["git", ["diff", "--check"]]
];

const syntaxOnly = process.argv.includes("--syntax");

function run(command, args) {
  execFileSync(command, args, { stdio: "inherit" });
}

for (const file of syntaxFiles) {
  run(process.execPath, ["--check", file]);
}

if (!syntaxOnly) {
  for (const [command, args] of auditCommands) {
    run(command, args);
  }
}
