#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
FRONTEND_DIR="$ROOT_DIR/frontend"
DOCS_DIR="$ROOT_DIR/docs"

mkdir -p "$DOCS_DIR/data" "$DOCS_DIR/demo" "$DOCS_DIR/public" "$DOCS_DIR/public/stakeholder-logos" "$DOCS_DIR/deutschlandkarte-project/data" "$DOCS_DIR/mitmachen"

cp "$FRONTEND_DIR/login/login.html" "$DOCS_DIR/login.html"
cp "$FRONTEND_DIR/login/set-password.html" "$DOCS_DIR/set-password.html"
cp "$FRONTEND_DIR/app/versorgungs-kompass.html" "$DOCS_DIR/versorgungs-kompass.html"
cp "$FRONTEND_DIR/app/hospitations-dokumentation.html" "$DOCS_DIR/hospitations-dokumentation.html"
cp "$FRONTEND_DIR/pages/mitmachen/versorgungs-netzwerk.html" "$DOCS_DIR/mitmachen/versorgungs-netzwerk.html"
cp "$FRONTEND_DIR/map/versorgungs-kompass-map.html" "$DOCS_DIR/versorgungs-kompass-map.html"
cp "$FRONTEND_DIR/map/versorgungs-kompass-map-teaser.html" "$DOCS_DIR/versorgungs-kompass-map-teaser.html"
cp "$FRONTEND_DIR/map/versorgungs-kompass-contact-mini-map.html" "$DOCS_DIR/versorgungs-kompass-contact-mini-map.html"
cp "$FRONTEND_DIR/demo/index.html" "$DOCS_DIR/demo/index.html"
cp "$FRONTEND_DIR/demo/demo.css" "$DOCS_DIR/demo/demo.css"
cp "$FRONTEND_DIR/demo/demo-app.js" "$DOCS_DIR/demo/demo-app.js"
if [ -f "$FRONTEND_DIR/demo/README.md" ]; then
  cp "$FRONTEND_DIR/demo/README.md" "$DOCS_DIR/demo/README.md"
fi
cp "$FRONTEND_DIR/login/auth-config.js" "$DOCS_DIR/auth-config.js"
cp "$FRONTEND_DIR/login/auth-guard.js" "$DOCS_DIR/auth-guard.js"
cp "$FRONTEND_DIR/login/auth-login.js" "$DOCS_DIR/auth-login.js"
cp "$FRONTEND_DIR/data/versorgungs-kompass-data.js" "$DOCS_DIR/data/versorgungs-kompass-data.js"
cp "$FRONTEND_DIR/data/versorgungs-kompass-data.csv" "$DOCS_DIR/data/versorgungs-kompass-data.csv"
cp "$FRONTEND_DIR/data/expertenkreis-data.js" "$DOCS_DIR/data/expertenkreis-data.js"
cp "$FRONTEND_DIR/data/demo-data.js" "$DOCS_DIR/data/demo-data.js"
cp "$FRONTEND_DIR/data/sector-registry.js" "$DOCS_DIR/data/sector-registry.js"
cp "$FRONTEND_DIR/data/stakeholder-data.js" "$DOCS_DIR/data/stakeholder-data.js"
cp "$FRONTEND_DIR/data/patienten-data.js" "$DOCS_DIR/data/patienten-data.js"
cp "$FRONTEND_DIR/data/supabase-config.js" "$DOCS_DIR/data/supabase-config.js"
cp "$FRONTEND_DIR/data/data-service.js" "$DOCS_DIR/data/data-service.js"
cp "$ROOT_DIR/public/gematik-logo.svg" "$DOCS_DIR/public/gematik-logo.svg"
cp "$ROOT_DIR/public/format-roundtable-hero.jpg" "$DOCS_DIR/public/format-roundtable-hero.jpg"
cp "$ROOT_DIR/public/versorgungs-kompass-logo.png" "$DOCS_DIR/public/versorgungs-kompass-logo.png"
cp "$ROOT_DIR/public/demo-person-lisa.svg" "$DOCS_DIR/public/demo-person-lisa.svg"
cp "$ROOT_DIR/public/demo-person-jens.svg" "$DOCS_DIR/public/demo-person-jens.svg"
rm -rf "$DOCS_DIR/public/stakeholder-logos"
mkdir -p "$DOCS_DIR/public/stakeholder-logos"
cp -R "$ROOT_DIR"/public/stakeholder-logos/. "$DOCS_DIR/public/stakeholder-logos/"
cp "$ROOT_DIR/public/manifest.webmanifest" "$DOCS_DIR/manifest.webmanifest"
cp "$ROOT_DIR/public/app-icon-32.png" "$DOCS_DIR/public/app-icon-32.png"
cp "$ROOT_DIR/public/app-icon-180.png" "$DOCS_DIR/public/app-icon-180.png"
cp "$ROOT_DIR/public/app-icon-192.png" "$DOCS_DIR/public/app-icon-192.png"
cp "$ROOT_DIR/public/app-icon-512.png" "$DOCS_DIR/public/app-icon-512.png"
cp "$FRONTEND_DIR/map/data/de-geojson.js" "$DOCS_DIR/deutschlandkarte-project/data/de-geojson.js"
cp "$FRONTEND_DIR/map/data/city-labels.js" "$DOCS_DIR/deutschlandkarte-project/data/city-labels.js"
cp "$FRONTEND_DIR/map/data/state-labels.js" "$DOCS_DIR/deutschlandkarte-project/data/state-labels.js"
cp "$FRONTEND_DIR/map/data/state-polygons.js" "$DOCS_DIR/deutschlandkarte-project/data/state-polygons.js"

perl -0pi -e 's#\.\./login/auth-#./auth-#g; s#\.\./map/versorgungs-kompass-#./versorgungs-kompass-#g; s#\.\./map/data/#./deutschlandkarte-project/data/#g; s#\.\./data/#./data/#g; s#\.\./login/login\.html#./login.html#g' "$DOCS_DIR/versorgungs-kompass.html"
perl -0pi -e 's#\.\./\.\./public/manifest\.webmanifest#./manifest.webmanifest#g; s#\.\./public/manifest\.webmanifest#./manifest.webmanifest#g; s#\.\./\.\./public/app-icon-#./public/app-icon-#g; s#\.\./public/app-icon-#./public/app-icon-#g' "$DOCS_DIR/versorgungs-kompass.html"
perl -0pi -e 's#\.\./pages/mitmachen/#./mitmachen/#g; s#\.\./mitmachen/#./mitmachen/#g' "$DOCS_DIR/versorgungs-kompass.html"
perl -0pi -e 's#\.\./login/auth-#./auth-#g; s#\.\./data/#./data/#g' "$DOCS_DIR/hospitations-dokumentation.html"
perl -0pi -e 's#\.\./\.\./public/manifest\.webmanifest#./manifest.webmanifest#g; s#\.\./public/manifest\.webmanifest#./manifest.webmanifest#g; s#\.\./\.\./public/app-icon-#./public/app-icon-#g; s#\.\./public/app-icon-#./public/app-icon-#g' "$DOCS_DIR/hospitations-dokumentation.html"
perl -0pi -e 's#\.\./\.\./\.\./public/#../public/#g; s#\.\./\.\./public/#../public/#g; s#\.\./public/#../public/#g; s#\.\./\.\./app/versorgungs-kompass\.html#../versorgungs-kompass.html#g; s#\.\./app/versorgungs-kompass\.html#../versorgungs-kompass.html#g' "$DOCS_DIR/mitmachen/versorgungs-netzwerk.html"
perl -0pi -e 's#\.\./map/versorgungs-kompass-map-teaser\.html#./versorgungs-kompass-map-teaser.html#g; s#\.\./data/#./data/#g; s#\.\./\.\./public/manifest\.webmanifest#./manifest.webmanifest#g; s#\.\./public/manifest\.webmanifest#./manifest.webmanifest#g; s#\.\./\.\./public/app-icon-#./public/app-icon-#g; s#\.\./public/app-icon-#./public/app-icon-#g' "$DOCS_DIR/login.html"
perl -0pi -e 's#\.\./map/versorgungs-kompass-map-teaser\.html#./versorgungs-kompass-map-teaser.html#g; s#\.\./data/#./data/#g; s#\.\./app/versorgungs-kompass\.html#./versorgungs-kompass.html#g; s#\.\./\.\./public/manifest\.webmanifest#./manifest.webmanifest#g; s#\.\./public/manifest\.webmanifest#./manifest.webmanifest#g; s#\.\./\.\./public/app-icon-#./public/app-icon-#g; s#\.\./public/app-icon-#./public/app-icon-#g' "$DOCS_DIR/set-password.html"
perl -0pi -e 's#\.\./login/auth-#./auth-#g; s#\.\./\.\./public/#./public/#g; s#\.\./public/#./public/#g; s#\.\./data/#__ROOT_DATA__/#g; s#\./data/#./deutschlandkarte-project/data/#g; s#__ROOT_DATA__/#./data/#g' "$DOCS_DIR/versorgungs-kompass-map.html"
perl -0pi -e 's#\.\./data/#__ROOT_DATA__/#g; s#\./data/#./deutschlandkarte-project/data/#g; s#__ROOT_DATA__/#./data/#g' "$DOCS_DIR/versorgungs-kompass-map-teaser.html" "$DOCS_DIR/versorgungs-kompass-contact-mini-map.html"
perl -0pi -e 's#loginPath: "../login/login.html"#loginPath: "./login.html"#; s#defaultPath: "../app/versorgungs-kompass.html"#defaultPath: "./versorgungs-kompass.html"#' "$DOCS_DIR/auth-config.js"
perl -0pi -e 's#"start_url": "../frontend/app/versorgungs-kompass.html"#"start_url": "./versorgungs-kompass.html"#; s#"start_url": "../app/versorgungs-kompass.html"#"start_url": "./versorgungs-kompass.html"#; s#"scope": "../"#"scope": "./"#; s#"src": "./app-icon-#"src": "./public/app-icon-#g' "$DOCS_DIR/manifest.webmanifest"
perl -0pi -e 's#\.\./\.\./public/stakeholder-logos/#./public/stakeholder-logos/#g; s#\.\./public/stakeholder-logos/#./public/stakeholder-logos/#g' "$DOCS_DIR/data/stakeholder-data.js"
perl -0pi -e 's#\.\./\.\./frontend/data/#../data/#g; s#\.\./\.\./data/#../data/#g' "$DOCS_DIR/demo/index.html"
perl -0pi -e 's#\.\./\.\./frontend/map/versorgungs-kompass-map\.html#../versorgungs-kompass-map.html#g; s#\.\./\.\./map/versorgungs-kompass-map\.html#../versorgungs-kompass-map.html#g; s#\.\./map/versorgungs-kompass-map\.html#../versorgungs-kompass-map.html#g' "$DOCS_DIR/demo/demo-app.js"

echo "GitHub Pages assets synchronized to docs/."
