{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "versorgungs-kompass.frontendFullname" . }}-nginx
  labels:
    {{- include "versorgungs-kompass.labels" . | nindent 4 }}
data:
  default.conf: |
{{ range .Values.frontend.hostRedirects | default (list) }}
    server {
      listen 8080;
      listen [::]:8080;
      server_name {{ .host | quote }};
      server_tokens off;

      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
      return 308 {{ printf "%s$request_uri" .targetOrigin | quote }};
    }

{{ end }}
{{ .Files.Get "files/frontend-default.conf" | indent 4 }}
{{- end }}
