{{- if and .Values.frontend.enabled .Values.frontend.authProxy.enabled .Values.frontend.authProxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "versorgungs-kompass.frontendAuthProxyServiceAccountName" . }}
  labels:
    {{- include "versorgungs-kompass.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-auth-proxy
automountServiceAccountToken: {{ .Values.frontend.authProxy.serviceAccount.automountServiceAccountToken }}
{{- end }}
