{{- if and .Values.frontend.enabled .Values.frontend.publicEntry.enabled .Values.frontend.publicEntry.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "versorgungs-kompass.frontendPublicServiceAccountName" . }}
  labels:
    {{- include "versorgungs-kompass.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-public
automountServiceAccountToken: {{ .Values.frontend.publicEntry.serviceAccount.automountServiceAccountToken }}
{{- end }}
