{{- if .Values.gke.managedCertificate.enabled -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "versorgungs-kompass.gkeManagedCertificateName" . }}
  labels:
    {{- include "versorgungs-kompass.labels" . | nindent 4 }}
spec:
  domains:
    {{- required "gke.managedCertificate.domains must contain at least one domain" .Values.gke.managedCertificate.domains | toYaml | nindent 4 }}
{{- end }}
