{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "versorgungs-kompass.fullname" . }}-api
  labels:
    {{- include "versorgungs-kompass.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "versorgungs-kompass.selectorLabels" . | nindent 6 }}
{{- if .Values.frontend.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "versorgungs-kompass.frontendFullname" . }}
  labels:
    {{- include "versorgungs-kompass.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "versorgungs-kompass.frontendSelectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
