-- First-class observation objects for the global Hospitation workbench.
create or replace function public._hospitation_try_parse_jsonb_20260717(value text)
returns jsonb
language plpgsql
immutable
as $$
begin
  return value::jsonb;
exception when others then
  return null;
end;
$$;

create table if not exists public.hospitation_observations (
  id text primary key,
  hospitation_id uuid not null references public.hospitations(id) on delete cascade,
  sequence integer,
  title text not null default 'Beobachtung',
  situation text,
  description text,
  process_phase text,
  problem_type text,
  impact text,
  observation_type text,
  evidence_type text not null default 'interpreted'
    check (evidence_type in ('directly_observed', 'reported', 'interpreted')),
  relevance_score integer check (relevance_score between 1 and 5),
  usage_recommendation text,
  involved_roles text[] not null default '{}'::text[],
  affected_products text[] not null default '{}'::text[],
  topics text[] not null default '{}'::text[],
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('active', 'archived')),
  archived_at timestamptz,
  archived_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id)
);

create index if not exists hospitation_observations_hospitation_idx
  on public.hospitation_observations(hospitation_id);
create index if not exists hospitation_observations_status_idx
  on public.hospitation_observations(status);
create index if not exists hospitation_observations_codes_idx
  on public.hospitation_observations(process_phase, problem_type);
create index if not exists hospitation_observations_evidence_idx
  on public.hospitation_observations(evidence_type);
create index if not exists hospitation_observations_roles_gin
  on public.hospitation_observations using gin(involved_roles);
create index if not exists hospitation_observations_products_gin
  on public.hospitation_observations using gin(affected_products);
create index if not exists hospitation_observations_payload_gin
  on public.hospitation_observations using gin(payload);

drop trigger if exists hospitation_observations_touch_updated_at on public.hospitation_observations;
create trigger hospitation_observations_touch_updated_at
before update on public.hospitation_observations
for each row execute function public.touch_updated_at();

create table if not exists public.hospitation_observation_changes (
  id bigint generated by default as identity primary key,
  observation_id text not null references public.hospitation_observations(id) on delete cascade,
  hospitation_id uuid not null references public.hospitations(id) on delete cascade,
  action text not null check (action in ('create', 'update', 'archive', 'restore')),
  before_value jsonb,
  after_value jsonb,
  changed_at timestamptz not null default now(),
  changed_by uuid references public.profiles(id)
);

create index if not exists hospitation_observation_changes_observation_idx
  on public.hospitation_observation_changes(observation_id, changed_at desc);

create or replace function public.log_hospitation_observation_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  change_action text;
begin
  if tg_op = 'INSERT' then
    change_action := 'create';
    insert into public.hospitation_observation_changes
      (observation_id, hospitation_id, action, after_value, changed_by)
    values (new.id, new.hospitation_id, change_action, to_jsonb(new), new.created_by);
    return new;
  end if;

  change_action := case
    when old.status <> new.status and new.status = 'archived' then 'archive'
    when old.status <> new.status and new.status = 'active' then 'restore'
    else 'update'
  end;
  insert into public.hospitation_observation_changes
    (observation_id, hospitation_id, action, before_value, after_value, changed_by)
  values (new.id, new.hospitation_id, change_action, to_jsonb(old), to_jsonb(new), new.updated_by);
  return new;
end;
$$;

revoke all on function public.log_hospitation_observation_change()
  from public, anon, authenticated;

drop trigger if exists hospitation_observations_log_change on public.hospitation_observations;
create trigger hospitation_observations_log_change
after insert or update on public.hospitation_observations
for each row execute function public.log_hospitation_observation_change();

-- Preserve stable observation ids and all less common qualitative fields in payload.
insert into public.hospitation_observations (
  id, hospitation_id, sequence, title, situation, description, process_phase,
  problem_type, impact, observation_type, evidence_type, relevance_score,
  usage_recommendation, involved_roles, affected_products, topics, payload,
  created_at, updated_at
)
select
  coalesce(nullif(observation->>'id', ''), 'observation-' || h.id::text || '-' || row_number() over (partition by h.id)) as id,
  h.id,
  nullif(observation->>'sequence', '')::integer,
  coalesce(nullif(observation->>'title', ''), 'Beobachtung'),
  coalesce(observation->>'situation', observation->>'situationContext'),
  coalesce(observation->>'description', observation->>'observed'),
  observation->>'processPhase',
  observation->>'problemType',
  observation->>'impact',
  observation->>'observationType',
  case when observation->>'evidenceType' in ('directly_observed', 'reported', 'interpreted')
    then observation->>'evidenceType' else 'interpreted' end,
  case when (observation->>'relevanceScore') ~ '^[1-5]$' then (observation->>'relevanceScore')::integer end,
  coalesce(observation->>'usageRecommendation', observation->>'nextUse'),
  array(select jsonb_array_elements_text(
    case
      when jsonb_typeof(coalesce(observation->'involvedRoles', observation->'affectedRoles')) = 'array'
        then coalesce(observation->'involvedRoles', observation->'affectedRoles')
      else '[]'::jsonb
    end
  )),
  array(select jsonb_array_elements_text(
    case when jsonb_typeof(observation->'affectedProducts') = 'array'
      then observation->'affectedProducts' else '[]'::jsonb end
  )),
  array(select jsonb_array_elements_text(
    case
      when jsonb_typeof(coalesce(observation->'topics', observation->'themes')) = 'array'
        then coalesce(observation->'topics', observation->'themes')
      else '[]'::jsonb
    end
  )),
  observation,
  coalesce(nullif(observation->>'createdAt', '')::timestamptz, h.created_at),
  coalesce(nullif(observation->>'updatedAt', '')::timestamptz, h.updated_at)
from public.hospitations h
cross join lateral jsonb_array_elements(
  case
    when jsonb_typeof(public._hospitation_try_parse_jsonb_20260717(h.documentation_outcome)->'observations') = 'array'
      then public._hospitation_try_parse_jsonb_20260717(h.documentation_outcome)->'observations'
    else '[]'::jsonb
  end
) observation
on conflict (id) do nothing;

-- Keep older documented free text visible as an explicitly interpreted legacy object.
insert into public.hospitation_observations (
  id, hospitation_id, title, situation, description, process_phase,
  evidence_type, usage_recommendation, payload, created_at, updated_at
)
select
  'legacy-observation-' || h.id::text,
  h.id,
  coalesce(nullif(h.contact_name, ''), nullif(h.organization_name, ''), 'Allgemeine Beobachtung'),
  coalesce(
    nullif(public._hospitation_try_parse_jsonb_20260717(h.documentation_outcome)->>'experience', ''),
    nullif(public._hospitation_try_parse_jsonb_20260717(h.documentation_outcome)->>'observation', ''),
    nullif(h.documentation_summary, '')
  ),
  concat_ws(E'\n\n',
    nullif(public._hospitation_try_parse_jsonb_20260717(h.documentation_outcome)->>'insight', ''),
    nullif(public._hospitation_try_parse_jsonb_20260717(h.documentation_outcome)->>'processNotes', ''),
    nullif(public._hospitation_try_parse_jsonb_20260717(h.documentation_outcome)->>'risks', '')
  ),
  'Sonstiges',
  'interpreted',
  'weiter validieren',
  jsonb_build_object(
    'id', 'legacy-observation-' || h.id::text,
    'title', coalesce(nullif(h.contact_name, ''), nullif(h.organization_name, ''), 'Allgemeine Beobachtung'),
    'situation', coalesce(nullif(h.documentation_summary, ''), h.documentation_outcome),
    'processPhase', 'Sonstiges',
    'evidenceType', 'interpreted',
    'usageRecommendation', 'weiter validieren',
    'legacy', true
  ),
  h.created_at,
  h.updated_at
from public.hospitations h
where not exists (
  select 1 from public.hospitation_observations o where o.hospitation_id = h.id
)
and (
  nullif(trim(coalesce(h.documentation_summary, '')), '') is not null
  or nullif(trim(coalesce(h.documentation_outcome, '')), '') is not null
)
on conflict (id) do nothing;

alter table public.hospitation_observations enable row level security;
alter table public.hospitation_observation_changes enable row level security;

grant select, insert, update on public.hospitation_observations to authenticated;
grant select on public.hospitation_observation_changes to authenticated;
grant select, insert, update, delete on public.hospitation_observations to service_role;
grant select, insert, update, delete on public.hospitation_observation_changes to service_role;

drop policy if exists "hospitation observations authenticated read active" on public.hospitation_observations;
create policy "hospitation observations authenticated read active"
on public.hospitation_observations for select to authenticated
using (
  (status <> 'archived' and exists (
    select 1 from public.hospitations h
    where h.id = hospitation_id and h.status <> 'Archiviert'
  ))
  or public.current_profile_role() = 'admin'
);

drop policy if exists "hospitation observations editor admin insert" on public.hospitation_observations;
create policy "hospitation observations editor admin insert"
on public.hospitation_observations for insert to authenticated
with check (public.current_profile_role() in ('editor', 'admin'));

drop policy if exists "hospitation observations editor admin update" on public.hospitation_observations;
create policy "hospitation observations editor admin update"
on public.hospitation_observations for update to authenticated
using (public.current_profile_role() in ('editor', 'admin'))
with check (public.current_profile_role() in ('editor', 'admin'));

drop policy if exists "hospitation observation changes authenticated read" on public.hospitation_observation_changes;
create policy "hospitation observation changes authenticated read"
on public.hospitation_observation_changes for select to authenticated
using (exists (
  select 1 from public.hospitation_observations o where o.id = observation_id
));

drop function public._hospitation_try_parse_jsonb_20260717(text);
