with physician_association_logo_metadata (id, logo_url, logo_source_url) as (
  values
    ('physician-spifa', 'public/stakeholder-logos/physician-associations/physician-spifa.png', 'https://spifa.de/wp-content/uploads/2021/07/SpiFa_Logo_2024_weiss.png'),
    ('physician-gfb', 'public/stakeholder-logos/physician-associations/physician-gfb.png', 'https://www.gfb-facharztverband.de/images/logo.png'),
    ('physician-marburger-bund', 'public/stakeholder-logos/physician-associations/physician-marburger-bund.svg', 'https://www.marburger-bund.de/themes/custom/mb/img/logo.svg'),
    ('physician-hartmannbund', 'public/stakeholder-logos/physician-associations/physician-hartmannbund.svg', 'https://www.hartmannbund.de/wp-content/uploads/2020/10/logocrop.svg'),
    ('physician-hausaerzteverband', 'public/stakeholder-logos/physician-associations/physician-hausaerzteverband.png', 'https://www.haev.de/typo3conf/ext/dhv_sitepackage/Resources/Public/Images/HAEV_Logo_Dachverband_rgb.png'),
    ('physician-virchowbund', 'public/stakeholder-logos/physician-associations/physician-virchowbund.svg', 'https://www.virchowbund.de/_assets/12ecccfe9186b84b10b2cda53d4b5e65/Icons/logo-virchowbund.svg'),
    ('physician-medi-geno', 'public/stakeholder-logos/physician-associations/physician-medi-geno.png', 'https://www.medi-verbund.de/wp-content/uploads/2020/11/logo@2x.png'),
    ('physician-bdi', 'public/stakeholder-logos/physician-associations/physician-bdi.svg', 'https://www.bdi.de/fileadmin/templates/gfx/bdi_logo.svg'),
    ('physician-bvkj', 'public/stakeholder-logos/physician-associations/physician-bvkj.svg', 'https://www.bvkj.de/fileadmin/templates/gfx/bvkj-logo.svg'),
    ('physician-bvf', 'public/stakeholder-logos/physician-associations/physician-bvf.svg', 'https://www.bvf.de/fileadmin/templates/gfx/BVF-Logo.svg'),
    ('physician-bva', 'public/stakeholder-logos/physician-associations/physician-bva.gif', 'https://www.augeninfo.de/bilder/bva_logo.gif'),
    ('physician-bda', 'public/stakeholder-logos/physician-associations/physician-bda.png', 'https://www.bda.de/images/BDA-Logo-150.png'),
    ('physician-bdc', 'public/stakeholder-logos/physician-associations/physician-bdc.webp', 'https://www.bdc.de/wp-content/themes/bdc/images/logo.png'),
    ('physician-bdr', 'public/stakeholder-logos/physician-associations/physician-bdr.png', 'https://www.radiologenverband.de/theme/site/logo.png'),
    ('physician-bvdd', 'public/stakeholder-logos/physician-associations/physician-bvdd.png', 'https://hilfe.bvdd.de/corporate-design/logo/'),
    ('physician-bvdu', 'public/stakeholder-logos/physician-associations/physician-bvdu.svg', 'https://urologie-gestalten.de/wp-content/uploads/2026/05/BvDU-Logo.svg'),
    ('physician-bvou', 'public/stakeholder-logos/physician-associations/physician-bvou.png', 'https://d38i6es1q63hoz.cloudfront.net/wp-content/themes/bvou/images/bvou-logo-desk-neu.png'),
    ('physician-bvhno', 'public/stakeholder-logos/physician-associations/physician-bvhno.svg', 'https://www.hno-aerzte.de/fileadmin/Bilder/CD-Elemente/HNO-Logo-white-on-orange.svg'),
    ('physician-bdl', 'public/stakeholder-logos/physician-associations/physician-bdl.png', 'https://layout.verwaltungsportal.de/10905/img/logo.png'),
    ('physician-bvoegd', 'public/stakeholder-logos/physician-associations/physician-bvoegd.svg', 'https://www.bvoegd.de/wp-content/themes/bvoegd/img/BVOEGD_Logo_1.svg'),
    ('physician-daeb', 'public/stakeholder-logos/physician-associations/physician-daeb.png', 'https://www.aerztinnenbund.de/pics/9/967.png'),
    ('physician-alm', 'public/stakeholder-logos/physician-associations/physician-alm.svg', 'https://www.alm-ev.de/wp-content/uploads/Media/ALM-Logos/alm-logo.svg'),
    ('physician-bao', 'public/stakeholder-logos/physician-associations/physician-bao.svg', 'https://www.operieren.de/common/img/Logo_BAO_n.svg'),
    ('physician-bdb', 'public/stakeholder-logos/physician-associations/physician-bdb.jpg', 'https://www.bundesverband-belegaerzte.de/fileadmin/vorlagen/bdb/logo-belegaerzte.jpg'),
    ('physician-bdnc', 'public/stakeholder-logos/physician-associations/physician-bdnc.png', 'https://commons.wikimedia.org/wiki/File:Bdnclogo.png'),
    ('physician-bdn-nuklearmedizin', 'public/stakeholder-logos/physician-associations/physician-bdn-nuklearmedizin.svg', 'https://www.berufsverband-nuklearmedizin.de/_assets/45db20552cef078ea65b34e606e1b5d6/Frontend/Images/bdn-logo.svg'),
    ('physician-bdnr', 'public/stakeholder-logos/physician-associations/physician-bdnr.svg', 'https://bdnr.de/themes/bdnr20/images/bdnr-logo-neu.svg'),
    ('physician-bdp-pneumologie', 'public/stakeholder-logos/physician-associations/physician-bdp-pneumologie.svg', 'https://www.pneumologenverband.de/build/img/bundesverband-pneumologie-schlaf-und-beatmungsmedizin-logo.6734c23e.svg'),
    ('physician-bdpm', 'public/stakeholder-logos/physician-associations/physician-bdpm.png', 'https://assets.coco-online.de/100601764588773_1lzRbZKb/logo-189-1658401122.png'),
    ('physician-bnc', 'public/stakeholder-logos/physician-associations/physician-bnc.svg', 'https://www.bncev.de/wp-content/themes/berufsverband-chirurgen-jersbek/src/img/logo-dark.svg'),
    ('physician-bnk', 'public/stakeholder-logos/physician-associations/physician-bnk.png', 'https://www.bnk.de/assets/images/0/bnk-ev_logo_2023-wmn8ee1k9yfm45c.png'),
    ('physician-bng', 'public/stakeholder-logos/physician-associations/physician-bng.png', 'https://bng-gastro.de/wp-content/uploads/2023/01/BNG-Logo-600.png'),
    ('physician-bngo', 'public/stakeholder-logos/physician-associations/physician-bngo.png', 'https://bngo.de/files/2021/11/Logo-BNGO-web.png'),
    ('physician-bnho', 'public/stakeholder-logos/physician-associations/physician-bnho.svg', 'https://bnho.de/wp-content/themes/bnho-fluxo-io/img/logos/logo-bnho-small.svg'),
    ('physician-brz', 'public/stakeholder-logos/physician-associations/physician-brz.png', 'https://repromed.org/wp-content/uploads/2017/05/cropped-logo.png'),
    ('physician-bvad', 'public/stakeholder-logos/physician-associations/physician-bvad.png', 'https://berufsverbandangiologie.de/wp-content/uploads/2020/07/LOGO_BVAD_01-1.png'),
    ('physician-bvdh', 'public/stakeholder-logos/physician-associations/physician-bvdh.png', 'https://www.bvdh.de/files/_theme_bvdh/img/BVDH/BVDH_LOGO_Web.png'),
    ('physician-bvnd', 'public/stakeholder-logos/physician-associations/physician-bvnd.png', 'https://www.bvnd.de/fileadmin/vorlagen/bvnd87/logo-bvnd.png'),
    ('physician-bvprm', 'public/stakeholder-logos/physician-associations/physician-bvprm.jpg', 'https://image.jimcdn.com/app/cms/image/transf/none/path/sc0e03c62217ca902/image/i5842f3a2b3800fd2/version/1641114701/image.jpg'),
    ('physician-dbvpp', 'public/stakeholder-logos/physician-associations/physician-dbvpp.jpg', 'https://www.dbvpp.de/logotxt.jpg'),
    ('physician-dfv', 'public/stakeholder-logos/physician-associations/physician-dfv.png', 'https://deutscher-facharztverband.de/wp-content/uploads/2022/09/cropped-cropped-logo-dfv.png'),
    ('physician-dgmkg', 'public/stakeholder-logos/physician-associations/physician-dgmkg.png', 'https://dgmkg.de/wp-content/uploads/2021/08/Logo_DGMKG_210x120.png'),
    ('physician-dgpraec', 'public/stakeholder-logos/physician-associations/physician-dgpraec.png', 'https://www.dgpraec.de/wp-content/uploads/2023/03/DGPRAeC_LOGO_128px_freigestellt.png'),
    ('physician-dn', 'public/stakeholder-logos/physician-associations/physician-dn.svg', 'https://www.dnev.de/site/templates/assets/img/core/dnev-signet-full-white.svg'),
    ('physician-vdro', 'public/stakeholder-logos/physician-associations/physician-vdro.svg', 'https://vdro.de/wp-content/uploads/sites/12/2024/01/vdro_logo_farbe_rgb.svg'),
    ('physician-bdh', 'public/stakeholder-logos/physician-associations/physician-bdh.png', 'https://www.hygiene-bv.de/daten/BDH_logo.png'),
    ('physician-bdp-pathologie', 'public/stakeholder-logos/physician-associations/physician-bdp-pathologie.png', 'https://www.pathologie.de/_Resources/Static/Packages/C4Csystems.Pathologie/GFX/logo-pathologie-175x50.png'),
    ('physician-bdrm', 'public/stakeholder-logos/physician-associations/physician-bdrm.png', 'https://bvd-rechtsmedizin.com/images/logo/LogoBVD_Transp.png'),
    ('physician-bdn-neurologen', 'public/stakeholder-logos/physician-associations/physician-bdn-neurologen.png', 'https://www.berufsverband-neurologen.de/wp-content/uploads/2020/09/BDN-Logo.png'),
    ('physician-bvdn', 'public/stakeholder-logos/physician-associations/physician-bvdn.png', 'https://www.berufsverband-nervenaerzte.de/wp-content/uploads/2021/04/BVDN-Logo.png'),
    ('physician-bvdp', 'public/stakeholder-logos/physician-associations/physician-bvdp.png', 'https://www.berufsverband-psychiater.de/wp-content/uploads/2021/03/BVDP-Logo_210219.png'),
    ('physician-bkjpp', 'public/stakeholder-logos/physician-associations/physician-bkjpp.jpg', 'https://www.bkjpp.de/wp-content/uploads/2024/03/logobkjjp60unten.jpg'),
    ('physician-aeda', 'public/stakeholder-logos/physician-associations/physician-aeda.svg', 'https://aeda.de/wp-content/uploads/2022/04/Aeda_Logo_lang.svg'),
    ('physician-bdrh', 'public/stakeholder-logos/physician-associations/physician-bdrh.svg', 'https://www.bdrh.de/wp-content/uploads/2021/12/BDRh_Logo_RGB_v1.svg'),
    ('physician-vlk', 'public/stakeholder-logos/physician-associations/physician-vlk.png', 'https://vlk-online.de/wp-content/uploads/thegem/logos/logo_6f12867f7839268a3c0b15b2f73017c0_3x.png'),
    ('physician-bvsd', 'public/stakeholder-logos/physician-associations/physician-bvsd.png', 'https://www.bvsd.de/wp-content/uploads/2019/05/bvsd_logo.png'),
    ('physician-freie-aerzteschaft', 'public/stakeholder-logos/physician-associations/physician-freie-aerzteschaft.png', 'https://freie-aerzteschaft.de/wp-content/uploads/2022/04/fa-logo-rgb-neu.png'),
    ('physician-ada', 'public/stakeholder-logos/physician-associations/physician-ada.png', 'https://www.arztnetze.info/images/logos/ada_logo.png')
)
update public.stakeholder_organizations as organization
set
  logo_url = physician_association_logo_metadata.logo_url,
  logo_source_url = physician_association_logo_metadata.logo_source_url,
  logo_source_label = 'Kuratiertes Logo-Asset: offizielles Header-/Logo-Asset; keine Favicon-/Social-Media-Quelle',
  updated_at = now()
from physician_association_logo_metadata
where organization.id = physician_association_logo_metadata.id;
