with physician_associations (
  id,
  name,
  organization_type,
  postal_code,
  city,
  federal_state,
  latitude,
  longitude,
  website,
  phone,
  email,
  member_count,
  member_count_source_url,
  member_count_source_label,
  member_count_updated_at,
  member_count_scope
) as (
  values
    ('physician-alm', 'ALM - Akkreditierte Labore in der Medizin e.V.', 'Labormedizinischer Interessenverband', '10117', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.alm-ev.de', '+49 30 4036884000', 'kontakt@alm-ev.de', 200, 'https://www.lobbyregister.bundestag.de/suche/R001160', 'Deutscher Bundestag Lobbyregister R001160, abgerufen 14.06.2026', date '2026-06-14', 'Über 200 medizinische Labore; zugleich etwa 900 Fachärztinnen und Fachärzte in vertretenen Laborstrukturen.'),
    ('physician-bao', 'Bundesverband Ambulantes Operieren e.V. (BAO)', 'Fachübergreifender Berufsverband Ambulantes Operieren', '10557', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.operieren.de', '+49 30 31958413', 'buero@bao.berlin', null, 'https://www.operieren.de/e42177/', 'Offizielles BAO-Impressum, abgerufen 14.06.2026', null, 'SpiFa-Mitgliedsverband; Interessenvertretung ambulanter operativer Versorgung.'),
    ('physician-bdb', 'Bundesverband der Belegärzte und Belegkrankenhäuser e.V. (BdB)', 'Fachübergreifender Berufsverband Belegarztwesen', '10557', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.bundesverband-belegaerzte.de', null, 'buero@bundesverband-belegaerzte.de', null, 'https://www.lobbyregister.bundestag.de/suche/R001659', 'Deutscher Bundestag Lobbyregister R001659, abgerufen 14.06.2026', null, 'Berufspolitische Vertretung des Belegarztwesens und der Belegkrankenhäuser.'),
    ('physician-bdnc', 'Berufsverband Deutsche Neurochirurgie e.V. (BDNC)', 'Fachärztlicher Berufsverband', null, null, null, null, null, 'https://bdnc.de/app/', null, null, null, 'https://spifa.de/verband/', 'SpiFa-Mitgliedsverbände, abgerufen 14.06.2026', null, 'Ordentlicher SpiFa-Mitgliedsverband für berufspolitische Belange der Neurochirurgie.'),
    ('physician-bdn-nuklearmedizin', 'Berufsverband Deutscher Nuklearmediziner e.V. (BDN)', 'Fachärztlicher Berufsverband', '45136', 'Essen', 'Nordrhein-Westfalen', 51.4556, 7.0116, 'https://www.berufsverband-nuklearmedizin.de', '+49 201 251297', 'herzogenrath@berufsverband-nuklearmedizin.de', 486, 'https://www.lobbyregister.bundestag.de/suche/R005526', 'Deutscher Bundestag Lobbyregister R005526, Stand 30.06.2025', date '2025-06-30', 'Natürliche und juristische Mitglieder des Berufsverbands Deutscher Nuklearmediziner.'),
    ('physician-bdnr', 'Berufsverband Deutscher Neuroradiologen e.V. (BDNR)', 'Fachärztlicher Berufsverband', '10587', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://bdnr.de', '+49 30 91607019', 'bdnr@drg.de', null, 'https://bdnr.de/impressum/', 'Offizielles BDNR-Impressum, abgerufen 14.06.2026', null, 'Ordentlicher SpiFa-Mitgliedsverband; vertritt Neuroradiologinnen und Neuroradiologen in Berufs-, Kammer- und Gesundheitspolitik.'),
    ('physician-bdp-pneumologie', 'Bundesverband der Pneumologie, Schlaf- und Beatmungsmedizin e.V. (BdP)', 'Fachärztlicher Berufsverband', '10117', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.pneumologenverband.de', '+49 30 700140445', null, null, 'https://www.lobbyregister.bundestag.de/suche/R000575', 'Deutscher Bundestag Lobbyregister R000575, abgerufen 14.06.2026', null, 'Berufsverband der Pneumologie, Schlaf- und Beatmungsmedizin; bundesweite Vertretung gegenüber Selbstverwaltung, Kassen und Politik.'),
    ('physician-bdpm', 'Bundesverband Psychosomatische Medizin und Ärztliche Psychotherapie e.V. (BDPM)', 'Fachärztlicher Berufsverband', '10999', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.bdpm-online.de', '+49 30 37918464', 'info@bdpm-online.de', null, 'https://www.bdpm-online.de/', 'Offizielle BDPM-Website, abgerufen 14.06.2026', null, 'SpiFa-Mitgliedsverband für Psychosomatische Medizin und Ärztliche Psychotherapie.'),
    ('physician-bnc', 'Berufsverband Niedergelassener Chirurgen e.V. (BNC)', 'Fachärztlicher Berufsverband', '22941', 'Jersbek', 'Schleswig-Holstein', 53.7410, 10.2190, 'https://www.bncev.de', '+49 4532 2687560', 'info@bncev.de', 1500, 'https://spifa.de/verband/', 'SpiFa-Mitgliedsverbände, abgerufen 14.06.2026', date '2026-06-14', 'Rund 1.500 freiberufliche Chirurginnen und Chirurgen laut SpiFa-Mitgliedsprofil.'),
    ('physician-bnk', 'Bundesverband Niedergelassener Kardiologen e.V. (BNK)', 'Fachärztlicher Berufsverband', '80805', 'München', 'Bayern', 48.1351, 11.5820, 'https://www.bnk.de', '+49 89 32357740', 'info@bnk.de', 1200, 'https://www.bnk.de/', 'Offizielle BNK-Website, abgerufen 14.06.2026', date '2026-06-14', 'Über 1.200 niedergelassene Fachärztinnen und Fachärzte mit Schwerpunkt Kardiologie.'),
    ('physician-bng', 'Berufsverband Niedergelassener Gastroenterologen Deutschlands e.V. (bng)', 'Fachärztlicher Berufsverband', '89081', 'Ulm', 'Baden-Württemberg', 48.4011, 9.9876, 'https://bng-gastro.de', '+49 731 7042718', 'kontakt@bng-gastro.de', 1300, 'https://bng-gastro.de/', 'Offizielle bng-Website, abgerufen 14.06.2026', date '2026-06-14', 'Mehr als 1.300 organisierte Ärztinnen und Ärzte; mehr als 90 Prozent der niedergelassenen Gastroenterologen.'),
    ('physician-bngo', 'Berufsverband Niedergelassener und ambulant tätiger Gynäkologischer Onkologen in Deutschland e.V. (BNGO)', 'Fachärztlicher Berufsverband', '15366', 'Neuenhagen bei Berlin', 'Brandenburg', 52.5290, 13.6890, 'https://bngo.de', '+49 3342 4268970', 'info@bngo.de', 123, 'https://bngo.de/', 'Offizielle BNGO-Website, abgerufen 14.06.2026', date '2026-06-14', 'Hochspezialisierte niedergelassene und ambulant tätige gynäkologische Onkologinnen und Onkologen.'),
    ('physician-bnho', 'Berufsverband der Niedergelassenen Ärztinnen und Ärzte für Hämatologie und Medizinische Onkologie in Deutschland e.V. (BNHO)', 'Fachärztlicher Berufsverband', '50677', 'Köln', 'Nordrhein-Westfalen', 50.9375, 6.9603, 'https://bnho.de', null, null, 590, 'https://bnho.de/', 'Offizielle BNHO-Website, abgerufen 14.06.2026', date '2026-06-14', 'Niedergelassene Fachärztinnen und Fachärzte für Hämatologie und Medizinische Onkologie.'),
    ('physician-brz', 'Bundesverband Reproduktionsmedizinischer Zentren Deutschlands e.V. (BRZ)', 'Fachärztlicher Berufsverband/Reproduktionsmedizinische Zentren', '66123', 'Saarbrücken', 'Saarland', 49.2402, 6.9969, 'https://repromed.de', '+49 681 373551', 'horstkamp@repromed.de', null, 'https://www.lobbyregister.bundestag.de/suche/R003685', 'Deutscher Bundestag Lobbyregister R003685, abgerufen 14.06.2026', null, 'Ordentlicher SpiFa-Mitgliedsverband für reproduktionsmedizinische Zentren.'),
    ('physician-bvad', 'Berufsverband der AngiologInnen Deutschlands e.V. (BVAD)', 'Fachärztlicher Berufsverband', '10437', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://berufsverbandangiologie.de', '+49 176 34383585', 'info@berufsverbandangiologie.de', null, 'https://www.lobbyregister.bundestag.de/suche/R005533', 'Deutscher Bundestag Lobbyregister R005533, abgerufen 14.06.2026', null, 'Berufs- und gesundheitspolitische Vertretung angiologisch tätiger Ärztinnen und Ärzte.'),
    ('physician-bvdh', 'Berufsverband Deutscher Humangenetiker e.V. (BVDH)', 'Fachärztlicher Berufsverband', '10115', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.bvdh.de', '+49 30 55954411', 'info@bvdh.de', null, 'https://www.bvdh.de/', 'Offizielle BVDH-Website, abgerufen 14.06.2026', null, 'Vertretung von Fachärztinnen und Fachärzten für Humangenetik, Fachhumangenetikerinnen und Fachhumangenetikern sowie genetischen Laborstrukturen.'),
    ('physician-bvnd', 'Bundesverband Niedergelassener Diabetologen e.V. (BVND)', 'Fachärztlicher Berufsverband', '89522', 'Heidenheim an der Brenz', 'Baden-Württemberg', 48.6768, 10.1510, 'https://www.bvnd.de', '+49 7321 9469190', 'mail@bvnd.de', null, 'https://www.lobbyregister.bundestag.de/suche/R000516', 'Deutscher Bundestag Lobbyregister R000516, abgerufen 14.06.2026', null, 'Bundesweite berufspolitische Interessenvertretung niedergelassener Diabetologinnen und Diabetologen.'),
    ('physician-bvprm', 'Berufsverband für Physikalische und Rehabilitative Medizin e.V. (BVPRM)', 'Fachärztlicher Berufsverband', '04357', 'Leipzig', 'Sachsen', 51.3397, 12.3731, 'https://www.bvprm.de', '+49 341 60051350', null, null, 'https://www.lobbyregister.bundestag.de/suche/R006811', 'Deutscher Bundestag Lobbyregister R006811, abgerufen 14.06.2026', null, 'Bundesweite berufspolitische Interessenvertretung der Physikalischen und Rehabilitativen Medizin.'),
    ('physician-dbvpp', 'Deutscher Berufsverband der Fachärzte für Phoniatrie und Pädaudiologie e.V. (DBVPP)', 'Fachärztlicher Berufsverband', null, null, null, null, null, 'https://www.dbvpp.de', null, null, null, 'https://spifa.de/verband/', 'SpiFa-Mitgliedsverbände, abgerufen 14.06.2026', null, 'Ordentlicher SpiFa-Mitgliedsverband für Phoniatrie und Pädaudiologie.'),
    ('physician-dfv', 'Deutscher Facharztverband e.V. (DFV)', 'Fachärztlicher Berufsverband', '89129', 'Langenau', 'Baden-Württemberg', 48.4964, 10.1180, 'https://www.deutscher-facharztverband.de', '+49 7345 9336785', null, null, 'https://www.lobbyregister.bundestag.de/suche/R002987', 'Deutscher Bundestag Lobbyregister R002987, abgerufen 14.06.2026', null, 'Unabhängige berufspolitische Vertretung niedergelassener Fachärztinnen und Fachärzte.'),
    ('physician-dgmkg', 'Deutsche Gesellschaft für Mund-, Kiefer- und Gesichtschirurgie e.V. (DGMKG)', 'Berufsverband und Fachgesellschaft', '65719', 'Hofheim', 'Hessen', 50.0906, 8.4497, 'https://www.dgmkg.com', '+49 6192 206303', 'info@dgmkg.de', 1900, 'https://spifa.de/verband/', 'SpiFa-Mitgliedsverbände, abgerufen 14.06.2026', date '2026-06-14', 'Gesamtverband aller Fachärztinnen und Fachärzte für Mund-, Kiefer- und Gesichtschirurgie in Deutschland.'),
    ('physician-dgpraec', 'Deutsche Gesellschaft für Plastische, Rekonstruktive und Ästhetische Chirurgie e.V. (DGPRÄC)', 'Berufsverband und Fachgesellschaft', '10117', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.dgpraec.de', '+49 30 44017611', 'info@dgpraec.de', 2000, 'https://www.dgpraec.de/', 'Offizielle DGPRÄC-Website, abgerufen 14.06.2026', date '2026-06-14', 'Über 2.000 Mitglieder; Berufsverband und wissenschaftliche Fachgesellschaft der Plastischen Chirurgie.'),
    ('physician-dn', 'Berufsverband der Nephrologinnen und Nephrologen in Deutschland e.V. (DN)', 'Fachärztlicher Berufsverband', '40210', 'Düsseldorf', 'Nordrhein-Westfalen', 51.2277, 6.7735, 'https://www.dnev.de', '+49 211 1795790', 'info@dnev.de', 737, 'https://www.lobbyregister.bundestag.de/suche/R000362', 'Deutscher Bundestag Lobbyregister R000362, Stand 01.12.2025', date '2025-12-01', 'Natürliche Mitglieder; berufspolitische Vertretung der nephrologischen Versorgung.'),
    ('physician-vdro', 'Verband der in Deutschland niedergelassenen Radioonkologen e.V. (VDRO)', 'Fachärztlicher Berufsverband', null, null, null, null, null, 'https://vdro.de', null, null, null, 'https://www.lobbyregister.bundestag.de/suche/R007040', 'Deutscher Bundestag Lobbyregister R007040, abgerufen 14.06.2026', null, 'Neu aufgenommener SpiFa-Mitgliedsverband für niedergelassene Radioonkologinnen und Radioonkologen.'),
    ('physician-bdh', 'Berufsverband Deutscher Hygieniker e.V. (BDH)', 'Fachärztlicher Berufsverband', '69129', 'Heidelberg', 'Baden-Württemberg', 49.3988, 8.6724, 'https://www.hygiene-bv.de', '+49 6221 3432381', 'info@hygiene-bv.de', null, 'https://www.gfb-facharztverband.de/de/gfb/mitglieder/bdh.html', 'GFB-Mitgliedsverband, abgerufen 14.06.2026', null, 'GFB-Mitgliedsverband für Fachärztinnen und Fachärzte für Hygiene und Umweltmedizin.'),
    ('physician-bdp-pathologie', 'Berufsverband Deutscher Pathologinnen und Pathologen e.V. (BDP)', 'Fachärztlicher Berufsverband', '10115', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.pathologie.de', '+49 30 30881970', 'bv@pathologie.de', null, 'https://www.lobbyregister.bundestag.de/suche/R002120', 'Deutscher Bundestag Lobbyregister R002120, abgerufen 14.06.2026', null, 'Berufsständische Vertretung der Pathologie und Neuropathologie in Praxis, Krankenhaus und Universität.'),
    ('physician-bdrm', 'Berufsverband Deutscher Rechtsmediziner e.V. (BDRM)', 'Fachärztlicher Berufsverband', '55131', 'Mainz', 'Rheinland-Pfalz', 49.9929, 8.2473, 'https://bvd-rechtsmedizin.com', '+49 6131 179487', null, null, 'https://www.gfb-facharztverband.de/de/gfb/mitglieder/bdrm.html', 'GFB-Mitgliedsverband, abgerufen 14.06.2026', null, 'GFB-Mitgliedsverband für Rechtsmedizin.'),
    ('physician-bdn-neurologen', 'Berufsverband Deutscher Neurologen e.V. (BDN)', 'Fachärztlicher Berufsverband', '12165', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.berufsverband-neurologen.de', '+49 30 94878310', 'info@berufsverband-neurologen.de', null, 'https://www.gfb-facharztverband.de/de/gfb/mitglieder/bdn.html', 'GFB-Mitgliedsverband, abgerufen 14.06.2026', null, 'Zentrale Interessenvertretung für Fachärztinnen und Fachärzte der Neurologie in Deutschland.'),
    ('physician-bvdn', 'Berufsverband Deutscher Nervenärzte e.V. (BVDN)', 'Fachärztlicher Berufsverband', '12165', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.berufsverband-nervenaerzte.de', '+49 30 94878310', 'info@bvdn.de', null, 'https://www.gfb-facharztverband.de/de/gfb/mitglieder/bvdn.html', 'GFB-Mitgliedsverband, abgerufen 14.06.2026', null, 'GFB-Mitgliedsverband; bundesweite Interessenvertretung der Nervenärztinnen und Nervenärzte.'),
    ('physician-bvdp', 'Berufsverband Deutscher Fachärztinnen und Fachärzte für Psychiatrie und Psychotherapie e.V. (BVDP)', 'Fachärztlicher Berufsverband', '12165', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.berufsverband-psychiater.de', '+49 30 94878310', 'info@berufsverband-psychiater.de', null, 'https://www.gfb-facharztverband.de/de/gfb/mitglieder/bvdp.html', 'GFB-Mitgliedsverband, abgerufen 14.06.2026', null, 'GFB-Mitgliedsverband für Psychiatrie und Psychotherapie.'),
    ('physician-bkjpp', 'Berufsverband für Kinder- und Jugendpsychiatrie, Psychosomatik und Psychotherapie in Deutschland e.V. (BKJPP)', 'Fachärztlicher Berufsverband', '55116', 'Mainz', 'Rheinland-Pfalz', 49.9929, 8.2473, 'https://www.bkjpp.de', '+49 6131 6938070', null, null, 'https://www.lobbyregister.bundestag.de/suche/R007652', 'Deutscher Bundestag Lobbyregister R007652, abgerufen 14.06.2026', null, 'Berufsverband für Kinder- und Jugendpsychiatrie, Psychosomatik und Psychotherapie.'),
    ('physician-aeda', 'Ärzteverband Deutscher Allergologen e.V. (AeDA)', 'Ärztlicher Berufsverband', '65205', 'Wiesbaden', 'Hessen', 50.0782, 8.2398, 'https://aeda.de', '+49 611 95008000', 'info@aeda.de', null, 'https://www.gfb-facharztverband.de/de/gfb/mitglieder/aeda.html', 'GFB-Mitgliedsverband, abgerufen 14.06.2026', null, 'Berufsverband angewandt allergologisch tätiger Ärztinnen und Ärzte.'),
    ('physician-bdrh', 'Berufsverband Deutscher Rheumatologen e.V. (BDRh)', 'Fachärztlicher Berufsverband', '82031', 'Grünwald', 'Bayern', 48.0399, 11.5232, 'https://www.bdrh.de', '+49 89 904141413', 'kontakt@bdrh.de', null, 'https://www.lobbyregister.bundestag.de/suche/R000342', 'Deutscher Bundestag Lobbyregister R000342, abgerufen 14.06.2026', null, 'Berufspolitische Vertretung rheumatologisch tätiger Ärztinnen und Ärzte.'),
    ('physician-vlk', 'Verband leitender Krankenhausärztinnen und -ärzte e.V. (VLK)', 'Ärztlicher Berufsverband Krankenhausleitung', '40474', 'Düsseldorf', 'Nordrhein-Westfalen', 51.2277, 6.7735, 'https://vlk-online.de', '+49 211 454990', 'info@vlk-online.de', null, 'https://www.lobbyregister.bundestag.de/suche/R001393', 'Deutscher Bundestag Lobbyregister R001393, abgerufen 14.06.2026', null, 'Bundesweite Interessenvertretung leitender Krankenhausärztinnen und Krankenhausärzte mit 16 Landesverbänden.'),
    ('physician-bvsd', 'Berufsverband der Ärzte und Psychologischen Psychotherapeuten in der Schmerz- und Palliativmedizin in Deutschland e.V. (BVSD)', 'Ärztlicher Berufsverband Schmerz- und Palliativmedizin', '10711', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.bvsd.de', '+49 30 28867260', 'bgst@bvsd.de', 600, 'https://www.bvsd.de/', 'Offizielle BVSD-Website, abgerufen 14.06.2026', date '2026-06-14', 'Rund 600 Mitglieder in der Schmerz- und Palliativmedizin; ärztlich-psychotherapeutischer Berufsverband.'),
    ('physician-freie-aerzteschaft', 'Freie Ärzteschaft e.V. (FÄ)', 'Ärztlicher Berufsverband', null, 'Essen', 'Nordrhein-Westfalen', 51.4556, 7.0116, 'https://freie-aerzteschaft.de', null, null, null, 'https://freie-aerzteschaft.de/', 'Offizielle Verbandsseite, abgerufen 14.06.2026', null, 'Fachübergreifender ärztlicher Berufsverband mit Schwerpunkt freie ärztliche Berufsausübung und ambulante Versorgung.'),
    ('physician-ada', 'AdA - Bundesverband der Arzt-, Praxis- und Gesundheitsnetze e.V.', 'Dachverband ärztlicher Praxis- und Gesundheitsnetze', '10117', 'Berlin', 'Berlin', 52.5200, 13.4050, 'https://www.arztnetze.info', '+49 30 403656700', null, 400, 'https://www.lobbyregister.bundestag.de/suche/R004210', 'Deutscher Bundestag Lobbyregister R004210, abgerufen 14.06.2026', date '2026-06-14', 'Rund 400 Arztnetze und Gesundheitsverbünde werden als bundesweite Netzwerkstruktur adressiert.')
)
insert into public.stakeholder_organizations (
  id,
  stakeholder_type_id,
  name,
  normalized_name,
  organization_type,
  postal_code,
  city,
  federal_state,
  latitude,
  longitude,
  website,
  phone,
  email,
  member_count,
  member_count_source_url,
  member_count_source_label,
  member_count_updated_at,
  member_count_scope,
  notes,
  source,
  status
)
select
  id,
  'physician-associations',
  name,
  lower(name),
  organization_type,
  postal_code,
  city,
  federal_state,
  latitude,
  longitude,
  website,
  phone,
  email,
  member_count,
  member_count_source_url,
  member_count_source_label,
  member_count_updated_at,
  member_count_scope,
  'Bundesweit relevante ärztliche Berufs-, Fach- oder Dachorganisation; Erweiterung nach SpiFa-/GFB-Mitgliedschaft, Lobbyregister-Relevanz, Versorgungspolitik und bundesweiter Kontaktierbarkeit.',
  'Recherche ärztliche Berufsverbände, Stand 14.06.2026',
  'active'
from physician_associations
on conflict (id) do update
set stakeholder_type_id = excluded.stakeholder_type_id,
    name = excluded.name,
    normalized_name = excluded.normalized_name,
    organization_type = excluded.organization_type,
    postal_code = excluded.postal_code,
    city = excluded.city,
    federal_state = excluded.federal_state,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    website = excluded.website,
    phone = excluded.phone,
    email = excluded.email,
    member_count = excluded.member_count,
    member_count_source_url = excluded.member_count_source_url,
    member_count_source_label = excluded.member_count_source_label,
    member_count_updated_at = excluded.member_count_updated_at,
    member_count_scope = excluded.member_count_scope,
    notes = excluded.notes,
    source = excluded.source,
    status = excluded.status;
