alter table if exists public.stakeholder_organizations
  add column if not exists logo_url text,
  add column if not exists logo_source_url text,
  add column if not exists logo_source_label text;

with logo_metadata (id, logo_url, logo_source_url) as (
  values
  ('health-insurance-aok-baden-wurttemberg', 'public/stakeholder-logos/health-insurance/aok.svg', 'https://commons.wikimedia.org/wiki/File:AOK-2021.svg'),
  ('health-insurance-aok-bayern', 'public/stakeholder-logos/health-insurance/aok.svg', 'https://commons.wikimedia.org/wiki/File:AOK-2021.svg'),
  ('health-insurance-aok-bremen-bremerhaven', 'public/stakeholder-logos/health-insurance/aok.svg', 'https://commons.wikimedia.org/wiki/File:AOK-2021.svg'),
  ('health-insurance-aok-hessen', 'public/stakeholder-logos/health-insurance/aok.svg', 'https://commons.wikimedia.org/wiki/File:AOK-2021.svg'),
  ('health-insurance-aok-niedersachsen', 'public/stakeholder-logos/health-insurance/aok.svg', 'https://commons.wikimedia.org/wiki/File:AOK-2021.svg'),
  ('health-insurance-aok-nordost', 'public/stakeholder-logos/health-insurance/aok.svg', 'https://commons.wikimedia.org/wiki/File:AOK-2021.svg'),
  ('health-insurance-aok-nordwest', 'public/stakeholder-logos/health-insurance/aok.svg', 'https://commons.wikimedia.org/wiki/File:AOK-2021.svg'),
  ('health-insurance-aok-plus', 'public/stakeholder-logos/health-insurance/health-insurance-aok-plus.svg', 'https://www.aok.de/aokplus'),
  ('health-insurance-aok-rheinland-pfalz-saarland', 'public/stakeholder-logos/health-insurance/aok.svg', 'https://commons.wikimedia.org/wiki/File:AOK-2021.svg'),
  ('health-insurance-aok-rheinland-hamburg', 'public/stakeholder-logos/health-insurance/aok.svg', 'https://commons.wikimedia.org/wiki/File:AOK-2021.svg'),
  ('health-insurance-aok-sachsen-anhalt', 'public/stakeholder-logos/health-insurance/health-insurance-aok-sachsen-anhalt.svg', 'https://www.aok.de/sachsen-anhalt'),
  ('health-insurance-audi-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-audi-bkk.svg', 'https://www.audibkk.de'),
  ('health-insurance-bahn-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-bahn-bkk.svg', 'https://commons.wikimedia.org/wiki/File:BAHN-BKK_RGB.svg'),
  ('health-insurance-barmer', 'public/stakeholder-logos/health-insurance/health-insurance-barmer.svg', 'https://commons.wikimedia.org/wiki/File:Barmer_Logo_12.2025.svg'),
  ('health-insurance-bergische-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-bergische-krankenkasse.png', 'https://www.bergische-krankenkasse.de'),
  ('health-insurance-bertelsmann-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-bertelsmann-bkk.svg', 'https://commons.wikimedia.org/wiki/File:Bertelsmann_BKK_Logo.svg'),
  ('health-insurance-big-direkt-gesund', 'public/stakeholder-logos/health-insurance/health-insurance-big-direkt-gesund.svg', 'https://www.big-direkt.de'),
  ('health-insurance-bkk-akzo-nobel-bayern', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-akzo-nobel-bayern.svg', 'https://www.bkk-akzo.de'),
  ('health-insurance-bkk-b-braun-aesculap', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-b-braun-aesculap.png', 'https://www.bkk-bba.de'),
  ('health-insurance-bkk-deutsche-bank-ag', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-deutsche-bank-ag.svg', 'https://de.wikipedia.org/wiki/Datei:BKK_Deutsche_Bank_Logo.svg'),
  ('health-insurance-bkk-diakonie', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-diakonie.png', 'https://www.bkk-diakonie.de'),
  ('health-insurance-bkk-durkoppadler', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-durkoppadler.png', 'https://www.bkk-da.de'),
  ('health-insurance-bkk-euregio', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-euregio.png', 'https://www.bkk-euregio.de'),
  ('health-insurance-bkk-evm', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-evm.svg', 'https://www.bkk-evm.de'),
  ('health-insurance-bkk-ewe', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-ewe.svg', 'https://www.bkk-ewe.de'),
  ('health-insurance-bkk-exklusiv', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-exklusiv.png', 'https://www.bkkexklusiv.de'),
  ('health-insurance-bkk-faber-castell-partner', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-faber-castell-partner.svg', 'https://commons.wikimedia.org/wiki/File:BKK_Faber_Castell_&_Partner_Logo.svg'),
  ('health-insurance-bkk-firmus', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-firmus.svg', 'https://www.bkk-firmus.de'),
  ('health-insurance-bkk-freudenberg', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-freudenberg.svg', 'https://commons.wikimedia.org/wiki/File:Freudenberg_BKK_Logo.svg'),
  ('health-insurance-bkk-gildemeister-seidensticker', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-gildemeister-seidensticker.svg', 'https://commons.wikimedia.org/wiki/File:BKK_Gildemeister_Seidensticker_logo.svg'),
  ('health-insurance-bkk-groz-beckert', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-groz-beckert.svg', 'https://www.bkk-gb.de'),
  ('health-insurance-bkk-herkules', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-herkules.svg', 'https://www.bkk-herkules.de/'),
  ('health-insurance-bkk-karl-mayer', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-karl-mayer.svg', 'https://www.karlmayer-bkk.de'),
  ('health-insurance-bkk-linde', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-linde.svg', 'https://www.bkk-linde.de/'),
  ('health-insurance-bkk-mahle', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-mahle.svg', 'https://www.bkk-mahle.de'),
  ('health-insurance-bkk-melitta-hmr', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-melitta-hmr.svg', 'https://www.bkk-melitta-hmr.de'),
  ('health-insurance-bkk-miele', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-miele.svg', 'https://commons.wikimedia.org/wiki/File:BKK_Miele_Logo.svg'),
  ('health-insurance-bkk-mtu', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-mtu.svg', 'https://www.bkk-mtu.de'),
  ('health-insurance-bkk-pfaff', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-pfaff.svg', 'https://commons.wikimedia.org/wiki/File:BKK-Pfaff-Logo.svg'),
  ('health-insurance-bkk-pfalz', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-pfalz.svg', 'https://www.bkkpfalz.de'),
  ('health-insurance-bkk-provita', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-provita.svg', 'https://www.bkk-provita.de'),
  ('health-insurance-bkk-public', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-public.svg', 'https://commons.wikimedia.org/wiki/File:BKK_Public_Logo.svg'),
  ('health-insurance-bkk-pwc', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-pwc.svg', 'https://www.bkk-pwc.de'),
  ('health-insurance-bkk-rieker-ricosta-weisser', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-rieker-ricosta-weisser.svg', 'https://www.bkk-rrw.de'),
  ('health-insurance-bkk-salzgitter', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-salzgitter.svg', 'https://commons.wikimedia.org/wiki/File:BKK_Salzgitter_Logo.svg'),
  ('health-insurance-bkk-sbh', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-sbh.svg', 'https://www.bkk-sbh.de'),
  ('health-insurance-bkk-scheufelen', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-scheufelen.png', 'https://www.bkk-scheufelen.de'),
  ('health-insurance-bkk-technoform', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-technoform.png', 'https://www.bkk-technoform.de'),
  ('health-insurance-bkk-vdn', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-vdn.svg', 'https://commons.wikimedia.org/wiki/File:BKK_VDN_Logo.svg'),
  ('health-insurance-bkk-verbundplus', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-verbundplus.svg', 'https://www.bkk-verbundplus.de'),
  ('health-insurance-bkk-werra-meissner', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-werra-meissner.svg', 'https://www.bkk-werra-meissner.de/'),
  ('health-insurance-bkk-wirtschaft-finanzen', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-wirtschaft-finanzen.png', 'https://www.bkk-wf.de'),
  ('health-insurance-bkk-wurth', 'public/stakeholder-logos/health-insurance/health-insurance-bkk-wurth.png', 'https://www.bkk-wuerth.de'),
  ('health-insurance-bkk24', 'public/stakeholder-logos/health-insurance/health-insurance-bkk24.svg', 'https://www.bkk24.de'),
  ('health-insurance-bmw-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-bmw-bkk.svg', 'https://commons.wikimedia.org/wiki/File:BMW_BKK_Logo_2020.svg'),
  ('health-insurance-bosch-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-bosch-bkk.svg', 'https://www.bosch-bkk.de'),
  ('health-insurance-continentale-betriebskrankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-continentale-betriebskrankenkasse.png', 'https://commons.wikimedia.org/wiki/File:Logo_CBKK.png'),
  ('health-insurance-dak-gesundheit', 'public/stakeholder-logos/health-insurance/health-insurance-dak-gesundheit.svg', 'https://commons.wikimedia.org/wiki/File:DAK-Gesundheit_logo.svg'),
  ('health-insurance-debeka-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-debeka-bkk.svg', 'https://www.debeka-bkk.de'),
  ('health-insurance-energie-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-energie-bkk.svg', 'https://www.energie-bkk.de'),
  ('health-insurance-ey-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-ey-bkk.svg', 'https://www.ey-bkk.de/'),
  ('health-insurance-heimat-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-heimat-krankenkasse.png', 'https://commons.wikimedia.org/wiki/File:Heimat_Krankenkasse_Logo.svg'),
  ('health-insurance-hek-hanseatische-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-hek-hanseatische-krankenkasse.png', 'https://www.hek.de'),
  ('health-insurance-hkk-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-hkk-krankenkasse.svg', 'https://www.hkk.de'),
  ('health-insurance-ikk-die-innovationskasse', 'public/stakeholder-logos/health-insurance/health-insurance-ikk-die-innovationskasse.png', 'https://www.die-ik.de'),
  ('health-insurance-ikk-brandenburg-und-berlin', 'public/stakeholder-logos/health-insurance/health-insurance-ikk-brandenburg-und-berlin.svg', 'https://www.ikkbb.de'),
  ('health-insurance-ikk-classic', 'public/stakeholder-logos/health-insurance/health-insurance-ikk-classic.svg', 'https://www.ikk-classic.de'),
  ('health-insurance-ikk-gesund-plus', 'public/stakeholder-logos/health-insurance/health-insurance-ikk-gesund-plus.svg', 'https://www.ikk-gesundplus.de'),
  ('health-insurance-ikk-sudwest', 'public/stakeholder-logos/health-insurance/health-insurance-ikk-sudwest.svg', 'https://www.ikk-suedwest.de'),
  ('health-insurance-kkh-kaufmannische-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-kkh-kaufmannische-krankenkasse.svg', 'https://www.kkh.de'),
  ('health-insurance-knappschaft', 'public/stakeholder-logos/health-insurance/health-insurance-knappschaft.png', 'https://www.knappschaft.de/'),
  ('health-insurance-koenig-bauer-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-koenig-bauer-bkk.svg', 'https://commons.wikimedia.org/wiki/File:BKK_Koenig_%26_Bauer_Logo.svg'),
  ('health-insurance-krones-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-krones-bkk.svg', 'https://www.krones-bkk.de'),
  ('health-insurance-mercedes-benz-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-mercedes-benz-bkk.svg', 'https://commons.wikimedia.org/wiki/File:Mercedes-Benz_BKK_Logo_2022.svg'),
  ('health-insurance-merck-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-merck-bkk.svg', 'https://www.merck-bkk.de'),
  ('health-insurance-mhplus-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-mhplus-bkk.svg', 'https://www.mhplus.de'),
  ('health-insurance-mkk-meine-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-mkk-meine-krankenkasse.svg', 'https://www.meine-krankenkasse.de'),
  ('health-insurance-mobil-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-mobil-krankenkasse.svg', 'https://www.mobil-krankenkasse.de'),
  ('health-insurance-novitas-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-novitas-bkk.png', 'https://www.novitas-bkk.de/'),
  ('health-insurance-pronova-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-pronova-bkk.svg', 'https://www.pronovabkk.de'),
  ('health-insurance-r-v-betriebskrankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-r-v-betriebskrankenkasse.svg', 'https://www.ruv-bkk.de'),
  ('health-insurance-salus-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-salus-bkk.svg', 'https://www.salus-bkk.de'),
  ('health-insurance-sbk', 'public/stakeholder-logos/health-insurance/health-insurance-sbk.svg', 'https://www.sbk.org/'),
  ('health-insurance-securvita-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-securvita-krankenkasse.png', 'https://www.securvita.de'),
  ('health-insurance-skd-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-skd-bkk.svg', 'https://www.skd-bkk.de'),
  ('health-insurance-svlfg-landwirtschaftliche-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-svlfg-landwirtschaftliche-krankenkasse.svg', 'https://www.svlfg.de'),
  ('health-insurance-sudzucker-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-sudzucker-bkk.png', 'https://www.xn--sdzucker-bkk-dlb.de'),
  ('health-insurance-techniker-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-techniker-krankenkasse.svg', 'https://www.tk.de'),
  ('health-insurance-tui-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-tui-bkk.svg', 'https://www.tui-bkk.de/'),
  ('health-insurance-viactiv-krankenkasse', 'public/stakeholder-logos/health-insurance/health-insurance-viactiv-krankenkasse.svg', 'https://www.viactiv.de'),
  ('health-insurance-vivida-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-vivida-bkk.svg', 'https://www.vividabkk.de'),
  ('health-insurance-wmf-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-wmf-bkk.png', 'https://commons.wikimedia.org/wiki/File:WMF_BKK_logo.svg'),
  ('health-insurance-zf-bkk', 'public/stakeholder-logos/health-insurance/health-insurance-zf-bkk.svg', 'https://www.zfbkk.de')
)
update public.stakeholder_organizations as organization
set
  logo_url = logo_metadata.logo_url,
  logo_source_url = logo_metadata.logo_source_url,
  logo_source_label = 'Kuratiertes Logo-Asset',
  updated_at = now()
from logo_metadata
where organization.id = logo_metadata.id;
