with hospital_association_people (id, organization_id, name, role) as (
  values
    ('hospital-association-baden-wuerttemberg-matthias-einwag', 'hospital-association-baden-wuerttemberg', 'Matthias Einwag', 'Hauptgeschäftsführer'),
    ('hospital-association-bayern-roland-engehausen', 'hospital-association-bayern', 'Roland Engehausen', 'Geschäftsführer'),
    ('hospital-association-berlin-marc-schreiner', 'hospital-association-berlin', 'RA Marc Schreiner, LL.M.', 'Geschäftsführer'),
    ('hospital-association-brandenburg-michael-jacob', 'hospital-association-brandenburg', 'Michael Jacob', 'Geschäftsführer'),
    ('hospital-association-bremen-judith-borsch', 'hospital-association-bremen', 'Dipl.-Kffr. Judith Borsch', 'Geschäftsführerin'),
    ('hospital-association-hamburg-claudia-brase', 'hospital-association-hamburg', 'Dr. Claudia Brase', 'Geschäftsführerin'),
    ('hospital-association-hessen-steffen-gramminger', 'hospital-association-hessen', 'Prof. Dr. Steffen Gramminger', 'Geschäftsführender Direktor'),
    ('hospital-association-mecklenburg-vorpommern-uwe-borchmann', 'hospital-association-mecklenburg-vorpommern', 'Uwe Borchmann', 'Geschäftsführer'),
    ('hospital-association-niedersachsen-helge-engelke', 'hospital-association-niedersachsen', 'Helge Engelke', 'Verbandsdirektor'),
    ('hospital-association-nordrhein-westfalen-matthias-blum', 'hospital-association-nordrhein-westfalen', 'Matthias Blum', 'Geschäftsführer'),
    ('hospital-association-rheinland-pfalz-andreas-wermter', 'hospital-association-rheinland-pfalz', 'Andreas Wermter', 'Geschäftsführer'),
    ('hospital-association-saarland-thomas-jakobs', 'hospital-association-saarland', 'Dr. Thomas Jakobs', 'Geschäftsführer'),
    ('hospital-association-sachsen-friedrich-muenchen', 'hospital-association-sachsen', 'Assessor jur. Friedrich R. München', 'Geschäftsführer'),
    ('hospital-association-sachsen-anhalt-goesta-heelemann', 'hospital-association-sachsen-anhalt', 'Dr. Gösta Heelemann', 'Geschäftsführer'),
    ('hospital-association-schleswig-holstein-patrick-reimund', 'hospital-association-schleswig-holstein', 'Patrick Reimund', 'Geschäftsführer'),
    ('hospital-association-thueringen-rainer-poniewass', 'hospital-association-thueringen', 'Rainer Poniewaß', 'Geschäftsführer')
)
insert into public.stakeholder_people (
  id,
  stakeholder_type_id,
  organization_id,
  organization,
  name,
  role,
  committee,
  city,
  federal_state,
  latitude,
  longitude,
  map_position_source,
  phone,
  topics,
  notes,
  source,
  profile_url,
  is_representative_assembly_member,
  status
)
select
  person.id,
  'hospital-associations',
  person.organization_id,
  org.name,
  person.name,
  person.role,
  'Geschäftsführung',
  org.city,
  org.federal_state,
  org.latitude,
  org.longitude,
  'organization',
  org.phone,
  array['Krankenhausversorgung', 'Landeskrankenhausgesellschaft']::text[],
  'Kontaktdaten beziehen sich auf die Geschäftsstelle laut DKG-Mitgliederseite.',
  'DKG-Mitgliederseite',
  org.website,
  false,
  'active'
from hospital_association_people as person
join public.stakeholder_organizations as org on org.id = person.organization_id
on conflict (id) do update
set stakeholder_type_id = excluded.stakeholder_type_id,
    organization_id = excluded.organization_id,
    organization = excluded.organization,
    name = excluded.name,
    role = excluded.role,
    committee = excluded.committee,
    city = excluded.city,
    federal_state = excluded.federal_state,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    map_position_source = excluded.map_position_source,
    phone = excluded.phone,
    topics = excluded.topics,
    notes = excluded.notes,
    source = excluded.source,
    profile_url = excluded.profile_url,
    is_representative_assembly_member = excluded.is_representative_assembly_member,
    status = excluded.status;
